export const LOGIN_OKAY = "LOGIN_OKAY";
export const LOGOUT = "LOGOUT";

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_OKAY = "MAKE_PAYMENT_OKAY";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";

export const SUBMIT_SURVEY_START = "SUBMIT_FORM_START";
export const SUBMIT_SURVEY_OKAY = "SUBMIT_SURVEY_OKAY";
export const SUBMIT_SURVEY_FAIL = "SUBMIT_SURVEY_FAIL";

export const FETCH_SURVEYS_START = "FETCH_SURVEYS_START";
export const FETCH_SURVEYS_OKAY = "FETCH_SURVEYS_OKAY";
export const FETCH_SURVEYS_FAIL = "FETCH_SURVEYS_FAIL";
