export const LOGIN_OKAY = "LOGIN_OKAY";
export const LOGOUT = "LOGOUT";

export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const MAKE_PAYMENT_OKAY = "MAKE_PAYMENT_OKAY";
export const MAKE_PAYMENT_FAIL = "MAKE_PAYMENT_FAIL";

export const SUBMIT_SURVEY_START = "SUBMIT_FORM_START";
export const SUBMIT_SURVEY_OKAY = "SUBMIT_SURVEY_OKAY";
export const SUBMIT_SURVEY_FAIL = "SUBMIT_SURVEY_FAIL";
